### ISSUE TITLE
What about handlebars vars in template?

### ISSUE THREAD

**Issue by djagya** [nickcv-ln/yii2-mandrill#10]
I see there is no way to configure extension to use handlebars vars in the app.
We can set default (mailchimp) template language as default and add possibility to configure preferable template language.
And in case of handlebars usage we should fill `global_merge_tags` (instead of `template_content`) with given params (and add merging to `setGlobalMergeVars` method) 

I can do a PR

**Comment by nickcv-ln** [comment]
Hi @djagya, when using mandrill templates the template_content is used to replace dynamic content tags

i.e.

``` html
<span mc:edit="WORD"></span>
```

while the global_merge_vars content is used to replace the handlebars

```
*|MERGEVAR|*
```

This is all currently being tested with my test template in my mandrill account.

How would you like to change the existing behavior?

**Comment by djagya** [comment]
Hi @nickcv-ln, in order to use handlebars language (http://blog.mandrill.com/handlebars-for-templates-and-dynamic-content.html) and all its features like loops, nicer brackets {{ }} and so on, we need to change variable `merge_language` in message array to `handlebars` - take a look at this example provided by Mandrill http://kbcdn.mandrill.com/handlebars-example-sendtemplate-api.txt .

I'm sure would be great to add configurable property `public $templateLanguage = self::LANGUAGE_MAILCHIMP`, that can be changed in app config to e.g.

``` php
'mailer' => [
...
'templateLanguage' => \nickcv\mandrill\Mailer::LANGUAGE_HANDLEBARS,
]
```

In that case props sent to `\Yii::$app->mailer->compose($template, $props)` will be inserted not in `template_content`, but in `global_merge_vars`

I can create a PR with tests if you want

**Comment by nickcv-ln** [comment]
Sure thing!

Go ahead and create the PR!

**Comment by djagya** [comment]
Thx!

**Comment by djagya** [comment]
@nickcv-ln i think, it could be closed. Don't forget to create new release please

**Comment by nickcv-ln** [comment]
Just did!

Thx again for the support, I really appreciated it!
:bow:

**Comment by djagya** [comment]
I was glad to help :)
