### ISSUE TITLE
HTML message body does not include layouts

### ISSUE THREAD

**Issue by hdogan** [nickcv-ln/yii2-mandrill#12]
As title describes, HTML body of the message only contains view file of the mail. Layouts are not rendered.

**Comment by nickcv-ln** [comment]
Hi @hdogan, unfortunately that is not a bug of my component but is the default behaviour of the Yii mailer class.

My component is calling `yii\mail\BaseMailer::compose` method directly when rendering the view files:

``` php
    /**
     * Composes the message using a Mandrill template if the useMandrillTemplates
     * settings is true.
     *
     * If mandrill templates are not being used or if no template with the given
     * name has been found it will fallback to the normal compose method.
     *
     * @inheritdoc
     * @since 1.2.0
     */
    public function compose($view = null, array $params = [])
    {
        if ($this->useMandrillTemplates) {
            /** @var Message $message */
            $message = parent::compose();
            $message->setTemplateData($view, $params, $this->templateLanguage);
            if ($this->useTemplateDefaults) {
                $message->enableTemplateDefaults();
            }
            return $message;
        }

        return parent::compose($view, $params);
    }
```

If you want to use layouts with emails follow the guide that you can find [here](http://www.yiiframework.com/doc-2.0/guide-tutorial-mailing.html)

**Comment by hdogan** [comment]
When I switch to SMTP transport _without_ changing any view/layout configuration, message body rendered with the layout correctly. There may be something related with the Mandrill API.

**Comment by nickcv-ln** [comment]
the layout by default is never loaded by any mailer, unless you specifically set the htmlLayout and textLayout properties of the Mailer.

Did you set up these values in your configuration file?

**Comment by hdogan** [comment]
No, I'm using default yii2-advanced app template and it's mailer configuration, only `viewPath` is set (as default in yii2-advanced).

The interesting part is that, if I use your package and check Mandrill API logs, only content between `body`  tag is shown as `html` part. So it crops the mail content. (view file does not contain body tags but layout is).

**Comment by nickcv-ln** [comment]
I've just run a few tests editing the layout inside /mail/layouts/html and adding inside the body some content

```
<body>
    <h1>Something</h1>
    <?php $this->beginBody() ?>
    <?= $content ?>
    <?php $this->endBody() ?>
</body>
```

The message I received contains the h1 tag and its content as intended.
Which part of your template is being cropped?

**Comment by hdogan** [comment]
doctype, html, head, meta tags.

**Comment by nickcv-ln** [comment]
mandrill is probably getting rid of that stuff as soon as it receives it.
You shouldn't be relying on them anyway because most mail clients strip them.

If you want to you can refer to [this guide](http://kb.mailchimp.com/templates/code/common-html-mistakes)

> CSS Used Incorrectly
> 
> Most email applications strip HEAD and BODY tags from incoming email to keep embedded CSS from interfering with their page CSS. We recommend you use  inline CSS or that you embed your CSS just above your content below the <BODY> tag.
