### ISSUE TITLE
no way to get Mandrill instance

### ISSUE THREAD

**Issue by mikk150** [nickcv-ln/yii2-mandrill#13]
There is no way to get Mandrill instance, so one could use Mandrill functions to do additional cool stuff

**Comment by mikk150** [comment]
#14

**Comment by nickcv-ln** [comment]
Hi @mikk150 !
what functionality where you exactly looking for when you decided to go for this approach?

**Comment by mikk150** [comment]
I needed to get list of templates in mandrill
I was going to this approach, because whenever new functionality comes to mandrill, we can use it instantly and not to hack up current mailer(because it works great)

**Comment by nickcv-ln** [comment]
It makes sense for some things are completely unrelated to the mailer.
I will merge the PR later on today, sorry for delay

**Comment by nickcv-ln** [comment]
the PR has been marged in and a new release has been created!
thanks for your contribution @mikk150
