### ISSUE TITLE
SSL error when sending email

### ISSUE THREAD

**Issue by gerald27** [nickcv-ln/yii2-mandrill#15]
Thanks for this yii2 extension but I'm getting problem sending email. It doesn't send and when I checked the log file I'm getting this error.

"A mandrill error occurred: Mandrill_HttpError - API call to messages/send failed: SSL certificate problem: unable to get local issuer certificate"

Regards,
Gerald

**Comment by nickcv-ln** [comment]
Hi @gerald27, sorry for the late reply.

The error is due to a php.ini configuration error.
