### ISSUE TITLE
Wrong implementation of method setHtmlBody()

### ISSUE THREAD

**Issue by allush** [nickcv-ln/yii2-mandrill#16]
```
public function setHtmlBody($html)
    {
        if (is_string($html)) {
            $this->_html = HtmlPurifier::process($html);
        }

        return $this;
    }
```

`HtmlPurifier::process($html)` It cuts a lot of styles from the property "style". for example 'border-radius' excluded from result html.

i think, that using `HtmlPurifier::process($html)`   is the wrong approach. better to use a simple assignment.

**Comment by nickcv-ln** [comment]
I'm ok about making the change, but maybe it should still be an option.

I could add a new configuration option for the module to choose whether or not you want to purify the html input. This would be useful in case the html text is coming from a user input.

**Comment by allush** [comment]
@nickcv-ln  good, option is ok.

**Comment by andrey-bahrachev** [comment]
@nickcv-ln Using `HtmlPurifier` within `setHtmlBody()` method absolutely doesn't make sense, because it totally strips out applied html layout thus making `htmlLayout` property useless which is wrong.

**Comment by nickcv-ln** [comment]
@andrey-bahrachev if the html body is coming from a for the purifier prevents the user from injecting potential malicious code, so I still think it could be an option, I can default it to false

**Comment by nickcv-ln** [comment]
the more I think about it the more I think you guys are right.
It's up to the developer really at this point.

I will just scrap the purifier from setHtmlBody

**Comment by andrey-bahrachev** [comment]
Yeah, it makes sense to make it optional, but don't use the purifier inside the `setHtmlBody()` method, put it into the `compose()` method of the `Mailer` class before the layout view is rendered.

**Comment by nickcv-ln** [comment]
@andrey-bahrachev I see what you mean.

Doing it now btw

**Comment by andrey-bahrachev** [comment]
Cool, thanks a lot!

**Comment by nickcv-ln** [comment]
@andrey-bahrachev looking at it right now the only way to do it on just the user input before I render the view is if I loop through every single parameter sent through the view and use the purifier on each one that is a string, basically ignoring every user input if they are part of an object sent as a parameter.

If I do apply the purifier to the rendered view there is the issue that It might strip some code that the developer actually wanted to be there.
Probably it would be best to leave the developer in charge of sanitising the user input.

**Comment by andrey-bahrachev** [comment]
Ah, that's right.

**Comment by nickcv-ln** [comment]
pushed the new release! thanks @andrey-bahrachev and @allush

**Comment by andrey-bahrachev** [comment]
Awesome! Thanks :)
