### ISSUE TITLE
Insert api_key dyanmically

### ISSUE THREAD

**Issue by shahzadthathal** [nickcv-ln/yii2-mandrill#17]
Hi,
I want to insert man drill api key dynamically, because this key is save in database, how is it possible?
I have asked this question on stackoverflow but not get success.

http://stackoverflow.com/questions/32689230/yii2-params-access-within-local-config-file-in-common-directory

**Comment by nickcv-ln** [comment]
hi @shahzadthathal as people explained to you the app itself is not instantiated yet when reading the config files.

The best way to do it would be to instantiate the component in the bootstrap process of the application, if you really want to read the value from the database.

**Comment by shahzadthathal** [comment]
Thank you,  I will try :+1:
