### ISSUE TITLE
Class 'Mandrill' not found

### ISSUE THREAD

**Issue by Imran-yousuf** [nickcv-ln/yii2-mandrill#18]
i download the the zip file and paste it in vendor/nickcv/mandril/... folder directory..
and add
 "nickcv/yii2-mandrill": "*"
 this to composer file, 
and write this line to my config/web.php file 
  'mailer' => [
        'class' => 'nickcv\mandrill\Mailer',
        'apikey' => 'YourApiKey',
        'useMandrillTemplates' => true,
          ],

its says Class 'Mandrill' not found. on line 98.

 try {
            $this->_mandrill = new Mandrill($this->_apikey);
        } catch (\Exception $exc) {
            \Yii::error($exc->getMessage());
            throw new \Exception('an error occurred with your mailer. Please check the application logs.', 500);
        }

i could not found any Mandrill calss in directory structure.

**Comment by nickcv-ln** [comment]
Hi @Imran-yousuf,
Mandrill is a dependency for this module, as you can see inside its composer file.
If you do not want to install the module through composer, as recommended in the readme file, you will have to manually install all its dependencies as well.

:smile:

**Comment by Imran-yousuf** [comment]
Hi nickcv-ln thanks for your reply, i understand all this stuff, i just add require 'src/Mandrill.php'; and 
require 'Message.php'; in your  mailer class and its works like charm. thank you.

**Comment by DerksArno** [comment]
For the people who don't understand, add "mandrill/mandrill": "*" to your composer.json file.

"require": {
        "nickcv/yii2-mandrill": "*",
        "mandrill/mandrill": "*"
},
