### ISSUE TITLE
HTML entities encoding problem in the subject.

### ISSUE THREAD

**Issue by andrey-bahrachev** [nickcv-ln/yii2-mandrill#19]
Hey!
I'm facing an HTML entities encoding problem in email subjects, namely when, for instance, subject contains an `&` character in it it ends up as `&amp`. So when a subject meant to be "Company & co." I receive "Company &amp: co." instead.
Can't seem to find how to change that behavior. Thanks in advance!

**Comment by nickcv-ln** [comment]
fixed the issue
