### ISSUE TITLE
class Mandrill not found error

### ISSUE THREAD

**Issue by mitchkett** [nickcv-ln/yii2-mandrill#22]
When I install the plugin via composer.phar and set the appropriate configuration values in web.php and params.php, I get the following error message when trying to send an email:

PHP Fatal error:  Class 'Mandrill' not found in /{APP_PATH}/vendor/nickcv/yii2-mandrill/Mailer.php on line 98

I see the "use Mandrill" line at the top of the Mailer.php file, but can't seem to figure out where it's supposed to load that class from.

Any help is appreciated.
Thanks.

**Comment by nickcv-ln** [comment]
Hi @mitchkett 

I believe you may have not installed the mandrill package that the extension depends upon.
In theory if you used composer to install my package it should have installed all the dependencies automatically.

**Comment by iceman2hot4u** [comment]
@mitchkett  I have the same problem. Did you manage to fix it?

**Comment by nickcv-ln** [comment]
@iceman2hot4u as I said previously composer should be installing the package for you.

**Comment by iceman2hot4u** [comment]
Composer installed 2 packages, one for Mandrill and another one for your module. The thing is that it doesn't recognize the Mandrill class. I tried to move them to the same folder and and still nothing.

**Comment by nickcv-ln** [comment]
the autoloader inside composer should be loading the class as well... moving things around won't make it work, because the autoloader expects each namespace to be into its own path.

**Comment by nickcv-ln** [comment]
I'd recommend that you check the auoload_namespace file inside the vendor/composer directory and check whether or not mandrill is in there.
