### ISSUE TITLE
Expand to other back-end service providers?

### ISSUE THREAD

**Issue by tom--** [nickcv-ln/yii2-mandrill#24]
Mailchimp has [made it clear](https://blog.mailchimp.com/important-changes-to-mandrill/) they don't want to be in the transaction email business. Many users are scrambling for replacements.

Is adding other providers, e.g. Sendgrid, something that would interest you, Nic?

**Comment by nickcv-ln** [comment]
Hi @tom-- 
I'm definitely willing to create modules for other providers, but I believe this one should stay as it is: I don't like the idea of having a bloated package that contains too much stuff when you are probably never going to use more than one provider at a time.

If you are interested in working together let me know!

**Comment by tom--** [comment]
Hi @nickcv-ln.

Your tests in yii2-mandrill appear to be quite extensive. To what extent might they be reusable with other providers? That was the main reason I asked the question above.

**Comment by nickcv-ln** [comment]
90% of the Message class and its test are reusable.
Most of the changes would be within the mailer class but it shouldn't be too much work.

Do you have a link to the other provider's documentation?

**Comment by tom--** [comment]
API here https://github.com/sendgrid/sendgrid-php

Docs here: https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html

**Comment by nickcv-ln** [comment]
I just checked and there's already a package for sendgrid for Yii2

https://github.com/bryglen/yii2-sendgrid

**Comment by tom--** [comment]
Yes. But nto as good as yours :)

If we come up with something (perhaps based on bryglen's Mailer) that uses your tests, I'll let you know.
