### ISSUE TITLE
MessageInterface image embed() issue

### ISSUE THREAD

**Issue by sandy0201** [nickcv-ln/yii2-mandrill#25]
Hi,

The MessageInterface embed() method does not seem to work for Mandrill.
I'm trying to embed our company logo into the mail header, it works for SwiftMailer but not for Mandrill. For Mandrill it only attaches the image as a file attachment but does not embed or show the image inline.

How can this issue be fixed?
Please assist urgently.

Thank you.
Kind regards.

**Comment by nickcv-ln** [comment]
Hi @sandy0201,

I'd be happy to help you but could you please give me more data to reproduce the error?

**Comment by sandy0201** [comment]
Hi @nickcv-ln 

In my code, I'm sending mail to user using a mail template, inside the template I have embedded the logo of our company. When using SwiftMailer it embeds the image properly but using Mandrill it shows no image. Below is the code in used in the mail template:

`<img src="<?= $message->embed( Yii::getAlias("@webroot/mail/banner.jpg")); ?>">`

And here's the screenshots of what I mean by SwiftMailer works and Mandrill doesn't work:
**SwiftMailer**

![image](https://cloud.githubusercontent.com/assets/2969051/13356163/baa50de0-dcac-11e5-8038-3fc884fa5963.png)

**Mandrill**

![image](https://cloud.githubusercontent.com/assets/2969051/13356123/7e35662a-dcac-11e5-9a43-ac6fd73e4dfd.png)

Kind regards.

**Comment by sandy0201** [comment]
Hi @nickcv-ln 

Have you had a chance to look at this issue/problem I'm experiencing yet?

Thank you.
Kind regards.

**Comment by nickcv-ln** [comment]
hi @sandy0201 could you please copy me the resulting html that you get in your email with mandrill?
I mostly care about the image tag that is supposed to be holding the image.

Nic

**Comment by sandy0201** [comment]
Hi @nickcv-ln 

Sorry for the late response.

Here's the html of the email that sent from Mandrill to Outlook:
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title></title>
    </head>
<body>
         <table width="100%">
    <tbody>
      <tr>
        <td align="center" style="background: #F2F2f2;">

```
  <table border="0" cellpadding="0" cellspacing="0" height="100%" width="650" style="background: #F2F2f2;">
    <tbody>
      <tr>
        <td>

          <table id="content" bgcolor="#FFF" border="0" cellpadding="0" cellspacing="0" height="100%">
            <tbody>
              <tr>
                <td valign="top">
                  <table id="hero" border="0" cellpadding="0" cellspacing="0" height="25" width="100%" style="background: #FFF; border:solid 1px #ECEAEA;">
                    <tr>
                      <td>
                       <table id="hero" border="0" align="center" cellpadding="0" cellspacing="0" height="100%" width="650">
                        <tbody>
                         <tr>
                          <td valign="middle" align="center">
                            <a href="#">
                                <img src=" - Recipients: [TO]  [CC]  [BCC] ">
                            </a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td valign="top">
                  <table>
                    <tr>
                      <td valign="top" style="color: #606060; font-family: Helvetica,Arial,sans-serif; font-size: 14px; line-height: 18px; padding:10px 25px 30px 25px">
                               <p>
```

<br /> <br />
Hi Tester Testing,<br />
<br />
You have just made a credit bundle purchase order for you company, Testing Company.<br />
Your order on 26-02-2016 17:09:25, for the credit bundle:<br />
<br />
Credits: 150<br />
Amount: R2 490.00<br />
<br />
has been successfully processed. Please find the attached proforma invoice and proceed with payment.<br />
<br />
Thank you.<br />
<br />
<br />
Kind regards,<br />
The Inspiration Lab Team<br />
<bt /></p>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td border="0" cellpadding="0" cellspacing="0" height="10">
      </td>
    </tr>
    <tr>
      <td>
        <table id="footer" style="background:#FFF; border:solid 1px #ECEAEA;" border="0" cellpadding="0" cellspacing="0" height="100%">
          <tbody>
           <tr>
            <td valign="top" style="
            color: #606060;
            font-family: Helvetica,Arial,sans-serif;
            font-size: 12px;
            line-height: 18px;
            padding:10px 25px 30px 10px
            ">
            This e-mail is intended solely for the use of the individual or entity to whom it is addressed. If you have received this e-mail in error please notify us on support@inspirationlab.io.
          </td>
        </tr>
      </tbody>
    </table>
  </td>
</tr>
<tr>
  <td>
    <table id="pre-footer" border="0" cellpadding="0" cellspacing="0" height="25">
      <tbody>
       <tr>
        <td>
        </td>
      </tr>
    </tbody>
  </table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</html>`

Thank you.

Kind regards.

**Comment by sandy0201** [comment]
Hi @nickcv-ln 

We still can't figure out why Mandrill does not embed the image (our logo) like SwiftMailer does.

How can this issue we're experiencing be resolved?
Please can you assist urgently.

Thank you.
Kind regards.

**Comment by softwerft** [comment]
Hi Sandy,
i took a look at the code, an there is small bug.
The function "embed" of the Message-Class does not return the correct value.
Change the return from "return $this;" to "return 'cid:'.ArrayHelper::getValue($options, 'fileName', basename($fileName));" and it works.

greetings sw

**Comment by sandy0201** [comment]
Hi @softwerft,

Thank you for your response.

That seems to work and fixed the problem.

Thanks once again.
Kind regards.
