### ISSUE TITLE
Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by Krakozaber** [nickcv-ln/yii2-mandrill#34]
php: v.8.0.1
yii: v.2.0.40
nickcv/yii2-mandrill: 1.8.0

PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /mnt/data/www/pirs/vendor/nickcv/yii2-mandrill/src/Message.php on line 1085
Error: Array and string offset access syntax with curly braces is no longer supported

**Comment by Krakozaber** [comment]
It fixed in the dev branch, pliz create a new tag.

https://github.com/nickcv-ln/yii2-mandrill/issues/33

**Comment by simialbi** [comment]
Done
