### ISSUE TITLE
Can we use merge_vars in templates?

### ISSUE THREAD

**Issue by ventayol** [nickcv-ln/yii2-mandrill#4]
I'm checking the documentation and the code and I don't see anywhere we can set the merve_vars for templates.
Is it possible?

**Comment by kozmenkoav** [comment]
Just pass an array of merge vars as a second parameter of ->compose() method
```php
\Yii::$app->mailer
    ->compose('mailViewName', $arrayOfMergeVars)
    ->setTo('email@email.com')
    ->send();
```

**Comment by nickcv-ln** [comment]
definitely!

**Comment by ventayol** [comment]
@nickcv-ln I've added a pull request to support global merge vars

**Comment by nickcv-ln** [comment]
Yeah I've seen that!
I will accept it later on and create the additional tests.

Thanks for the help @ventayol
