### ISSUE TITLE
Using default values from template

### ISSUE THREAD

**Issue by kozmenkoav** [nickcv-ln/yii2-mandrill#6]
Small but useful update.
Mandrill uses default values for sender name and email from template if they haven't been passed through the API.
![screenshot_150422_171000](https://cloud.githubusercontent.com/assets/10463708/7276481/80f4cd30-e912-11e4-827c-f1e587caa8c9.png)
In case of using external templates it is important to leave them equal NULL instead of setting default values from app params:

``` php
private function getFromAddress()
{
    return $this->_fromAddress ? $this->_fromAddress : \Yii::$app->params['adminEmail'];
}
...
private function getFromName()
{
    return $this->_fromName ? $this->_fromName : \Yii::$app->name;
}
```

**Comment by nickcv-ln** [comment]
I think this could be an additional flag in the settings of the module because we cannot be sure that default values were set for the template

``` php
'mailer' => [
    'class' => 'nickcv\mandrill\Mailer',
    'apikey' => 'YourApiKey',
    'useMandrillTemplates' => false, // defaults to false
    'useTemplateDefaults' => true, // defaults to true but has no effect if the previous setting is not enabled
],
```
