### ISSUE TITLE
Не отправляются письма

### ISSUE THREAD

**Issue by DarkDrim** [nickcv-ln/yii2-mandrill#8]
Добрый день, установил пакет, указал api-ключ, все как описано.
На сайте https://mandrillapp.com/ добавил subaccounts, шаблон, потом пытаюсь отправить сообщение:

``` php
 \Yii::$app->mailer
            ->compose('mailViewName', ['x' => '222'])
            ->setFrom('test1@ya.ru')
            ->setTo('test2@ukr.net')
            ->setSubject('subject!!!')
            ->send();
```

Метод send() возвращает true, однако сообщение НЕ отправляется.
В чем может быть проблема?
Спасибо заранее!

**Comment by DarkDrim** [comment]
На сайте https://mandrillapp.com написано "Sending for your account has been paused. We have detected some unusual activity with your sending or signup. Please request an account review.". Может в этом дело?

**Comment by nickcv-ln** [comment]
Sorry, unfortunately I do not speak russian.
From the error you are getting I can tell that your account has been blacklisted by Mandrill itself, I'd recommend contacting their support service.

**Comment by DarkDrim** [comment]
I just checked into madrill, I entered their data and all. Location blacklist?
Thanks for the answer!

**Comment by nickcv-ln** [comment]
Could be, but it is definitely something on their end.

**Comment by DarkDrim** [comment]
Thanks
