### ISSUE TITLE
Sending to multiple recipients

### ISSUE THREAD

**Issue by DarkDrim** [nickcv-ln/yii2-mandrill#9]
Good day!
Is it possible to make a sending to multiple recipients separately? That they did not know who else to post?

**Comment by DarkDrim** [comment]
I realized that it is necessary to use the preserve_recipients, or not?

**Comment by nickcv-ln** [comment]
I'm not too sure I understand what you are trying to accomplish.
If I'm not mistaken you'd like to send the same email to multiple addresses keeping all of them in the TO field so that basically each one of them can see who else received the message.

Is that correct?

**Comment by DarkDrim** [comment]
Yes

**Comment by nickcv-ln** [comment]
As you thought to achieve this result you can just change the default setting in your account.

At the current time the extension for yii does not provide a method to override this value with every single email.

If you want to change the default setting for your account you can just follow the instructions on this page:

https://mandrill.zendesk.com/hc/en-us/articles/205582557-Can-I-send-to-more-than-one-recipient-at-a-time-

**Comment by DarkDrim** [comment]
Thank you very much
